name: Update Dictionary on GitHub Pages

on:
  push:
    branches:
      - main # Trigger when you push to the main branch
  schedule:
    # Runs daily at 6:35 AM UTC (11:35 PM PDT / 10:35 PM PST)
    - cron: '45 6 * * *' 
  workflow_dispatch: {} # Allows manual triggering from the GitHub Actions UI

jobs:
  update_dictionary:
    runs-on: ubuntu-latest
    permissions: # <--- ADD THIS BLOCK
      contents: write # <--- AND THIS LINE

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate dictionary.json
      run: |
        mkdir -p pokeking-translator # Ensure the directory exists
        curl -o pokeking-translator/dictionary.json "https://script.google.com/macros/s/AKfycbwec1juqGwtrBroLbUEz3tACHXrjS7JKjHhPY7C3Puq_uHohV5bZWduQbPzqG1kclVc/exec"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git update-index --refresh
        git diff-index --quiet HEAD -- || (git add pokeking-translator/dictionary.json && git commit -m "Automated dictionary update")
        git push
