name: Update Dictionary on GitHub Pages

on:
  push:
    branches:
      - main # Trigger when you push to the main branch
  schedule:
      # Runs daily at 7:05 AM UTC (11:05 PM PST)
      - cron: '20 7 * * *'
  workflow_dispatch: {} # Allows manual triggering from the GitHub Actions UI

jobs:
  update_dictionary:
    runs-on: ubuntu-latest
    permissions: # <--- ADD THIS BLOCK
      contents: write # <--- AND THIS LINE

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate dictionary.json
      run: |
        mkdir -p pokeking-translator 
        curl -o pokeking-translator/dictionary.json "https://script.google.com/macros/s/AKfycbxCamQitK4Jrl2FG4l2oMNhK0orW1I3mtrTvMRoV7JHgc8fQTSoOuiG6Q1D5L-UybfM/exec"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git update-index --refresh # Checks if there are any changes
        # Only add and commit if there are actual changes
        if ! git diff-index --quiet HEAD --; then
          git add pokeking-translator/dictionary.json
          git commit -m "Automated dictionary update"
          git push
        else
          echo "No changes to dictionary.json, skipping commit."
        fi
